[versions]
swt = "3.129.0"
slf4j = "2.0.17"
guice = "7.0.0"
junit = "5.14.1"
commons-cli = "1.11.0"
commons-net = "3.12.0"
commons-vfs = "2.10.0"
jcifs = "1.3.17"
jsch = "0.1.55"
hamcrest = "3.0"
testcontainers = "1.21.3"
spotless = "7.2.1"

[libraries]
commons-cli = { module = "commons-cli:commons-cli", version.ref = "commons-cli" }
commons-net = { module = "commons-net:commons-net", version.ref = "commons-net" }
commons-vfs = { module = "org.apache.commons:commons-vfs2", version.ref = "commons-vfs" }
jcifs = { module = "jcifs:jcifs", version.ref = "jcifs" }
jsch = { module = "com.jcraft:jsch", version.ref = "jsch" }
jcl-over-slf4j = { module = "org.slf4j:jcl-over-slf4j", version.ref = "slf4j" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
guice = { module = "com.google.inject:guice", version.ref = "guice" }
guice-assistedInject = { module = "com.google.inject.extensions:guice-assistedinject", version.ref = "guice" }
# so dependency update tooling can update the version automatically
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-junit = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }

[bundles]

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
sonarqube = { id = "org.sonarqube", version = "6.3.1.5724" }
versions = { id = "com.github.ben-manes.versions", version = "0.53.0" }
spotbugs = { id = "com.github.spotbugs", version = "6.4.5" }
offlineDependencies = { id = "io.pry.gradle.offline_dependencies", version = "0.5.0" }
findsecbugsPlugin = { id = "com.h3xstream.findsecbugs:findsecbugs-plugin", version = "1.14.0" }
